### ISSUE TITLE
Percentage gets converted to decimal value inside max()

### ISSUE THREAD

**Issue by stevepiron** [ben-eb/gulp-cssnano#108]
CSS source:

```css
.wrapper {
  padding: 0 6.66667%;
  padding: 0 calc(6.66667% + 0px);
  padding: 0 calc(max(6.66667%, env(safe-area-inset-right))) 0 calc(max(6.66667%, env(safe-area-inset-left))); /* Fine */
}
```

Minified CSS (prettified):

```css
.wrapper {
  padding:0 6.66667%;
  padding:0 calc(6.66667% + 0px);
  padding:0 calc(max(0.0666667, env(safe-area-inset-right))) 0 calc(max(0.0666667, env(safe-area-inset-left))); /* Problem is here */
}
```

**Comment by stevepiron** [comment]
For some reason, setting `calc: {preserve: true}` fixes it, but keeps the line with decimals and the line with the percentages.

Minified CSS (prettified):

```css
.wrapper {
  padding: 0 6.66667%;
  padding: 0 calc(6.66667% + 0px);
  padding: 0 calc(max(0.0666667, env(safe-area-inset-right))) 0 calc(max(0.0666667, env(safe-area-inset-left))); /* Problem is here */
  padding: 0 calc(max(6.66667%, env(safe-area-inset-right))) 0 calc(max(6.66667%, env(safe-area-inset-left))); /* Good! */
}
```

**Note:** I don't need the line `padding: 0 calc(6.66667% + 0px);`, it's just there to show that `calc()` is probably not to blame.
