### ISSUE TITLE
CSS3 Animation not working after minify

### ISSUE THREAD

**Issue by nmfzone** [ben-eb/gulp-cssnano#33]
I have css like so

```
.clock #point {
    -moz-animation: mymove 1s ease infinite;
    -webkit-animation: mymove 1s ease infinite;
    padding-left: 10px;
    padding-right: 10px;
}

@-webkit-keyframes mymove {
  0% {
    opacity: 1.0;
    text-shadow: 0 0 20px #00c6ff;
  }

  50% {
    opacity: 0;
    text-shadow: none;
  }

  100% {
    opacity: 1.0;
    text-shadow: 0 0 20px #00c6ff;
  }
}

@-moz-keyframes mymove {
    0% {
        opacity: 1.0;
        text-shadow: 0 0 20px #00c6ff;
    }

    50% {
        opacity: 0;
        text-shadow: none;
    }

    100% {
        opacity: 1.0;
        text-shadow: 0 0 20px #00c6ff;
    }
}
```

Previously, it works as normal. But, after i minified it, my css doesn't work. I'm not sure if i do something wrong.
I believe that because `100%` was replaced by `to`.

**Comment by ben-eb** [comment]
Looks like the `@-moz-keyframes` rule is removed. Does it work properly if you disable autoprefixer?

```js
var gulp = require('gulp');
var cssnano = require('gulp-cssnano');

gulp.task('default', function () {
    return gulp.src('./main.css')
        .pipe(cssnano({autoprefixer: false}))
        .pipe(gulp.dest('./out'));
});
```

**Comment by ben-eb** [comment]
By the way, `@-moz-keyframes` are unnecessary according to the caniuse data. You should add the unprefixed keyframes instead;

```css
.clock #point {
    -webkit-animation: mymove 1s ease infinite;
    animation: mymove 1s ease infinite;
    padding-left: 10px;
    padding-right: 10px;
}

@-webkit-keyframes mymove {
  0% {
    opacity: 1.0;
    text-shadow: 0 0 20px #00c6ff;
  }

  50% {
    opacity: 0;
    text-shadow: none;
  }

  100% {
    opacity: 1.0;
    text-shadow: 0 0 20px #00c6ff;
  }
}

@keyframes mymove {
    0% {
        opacity: 1.0;
        text-shadow: 0 0 20px #00c6ff;
    }

    50% {
        opacity: 0;
        text-shadow: none;
    }

    100% {
        opacity: 1.0;
        text-shadow: 0 0 20px #00c6ff;
    }
}
```

http://caniuse.com/#feat=css-animation

**Comment by mikestreety** [comment]
Could you not just have the unprefixed and let an autoprefixer put in the webkit ones?

**Comment by binarykitchen** [comment]
had the same problem - setting `'postcss-reduce-idents'` to false worked for me because it overlapped an external css file having keyframes i was including for the same page.

**Comment by librisius** [comment]
I have the same problem with -ms-transform: translateX(-50%);

**Comment by librisius** [comment]
it's still needed for win7 ie9
I mean -ms-transform: translateX(-50%);

**Comment by ben-eb** [comment]
@librisius Does `{autoprefixer: false}` resolve your issue?

**Comment by saada** [comment]
@ben-eb , not for me.

**Comment by ben-eb** [comment]
@saada What is the exact code you are having problems with?

Also, @nmfzone `100%` is equivalent to `to` as defined in the spec, so the browser is incorrect not this tool.

> The keyframe selector for a keyframe style rule consists of a comma-separated list of percentage values or the keywords ‘from’ or ‘to’. The selector is used to specify the percentage along the duration of the animation that the keyframe represents. The keyframe itself is specified by the block of property values declared on the selector. The keyword ‘from’ is equivalent to the value ‘0%’. The keyword ‘to’ is equivalent to the value ‘100%’. Note that the percentage unit specifier must be used on percentage values. Therefore, ‘0’ is an invalid keyframe selector.

https://www.w3.org/TR/css3-animations/

**Comment by librisius** [comment]
@ben-eb yes it does, thanks

**Comment by saada** [comment]
my gulpfile.js looks like this
```js
gulp.task('less', function () {
    gulp.src('./css/*.less')
        .pipe(less())
        .pipe(postcss([ autoprefixer({ browsers: ['> 5%'] }) ]))
        .pipe(cssnano({autoprefixer: false}))
        .pipe(gulp.dest('./css'));
});
```
I also tried including cssnano in the postcss array with no success.
anyway, here's the less file.

```less
@circle-diameter: 12px;
@animation-speed: 1.0s;

.spinner {
  width: 70px;
  text-align: center;
  position: fixed;
  z-index: 10000; //modals hide the spinner if below 10000
  top: 50%;
  left: 50%;
  margin-left: -35px;
  margin-top: -20px;
  height: 40px;
  line-height: 40px;
  background: rgba(255,255,255,0.6);
  border-radius: 0.4em;

  & > div {
    width: @circle-diameter;
    height: @circle-diameter;
    background-color: #3498DB;

    border-radius: 100%;
    display: inline-block;
    animation: sk-bouncedelay @animation-speed infinite ease-in-out both;
  }

  & .bounce1 {
    animation-delay: -0.32s;
    background-color: #3498DB;
  }

  & .bounce2 {
    animation-delay: -0.16s;
    background-color: #3498DB;
  }
}

@keyframes sk-bouncedelay {
  0%, 80%, 100% {
    transform: scale(0);
  }
  40% {
    transform: scale(1.0);
  }
}
```
