### ISSUE TITLE
IE asterisk hack mishandled with mergeLonghand

### ISSUE THREAD

**Issue by lonekorean** [ben-eb/gulp-cssnano#53]
There's a hack for old IE where you prefix a style with `*` and only old IE will use that style. For example, `*padding-top: 2px;` will be honored by old IE and ignored by modern browsers.

But with the mergeLonghand optimization, this hack is lost, resulting in incorrect styles. For example, this:

```css
body {
	*padding-top: 2px;
	padding-left: 4px;
	*padding-bottom: 2px;
	padding-right: 4px;
}
```

Becomes this, even though they are not equivalent:

```css
body{padding:2px 4px}
```

I came across this while using an older version of Bootstrap that still employs the IE asterisk hack.
