### ISSUE TITLE
single quote may cause problem

### ISSUE THREAD

**Issue by DirtyHao** [ben-eb/gulp-cssnano#70]
when i use this plugins
       singl quote in my css files has cause a problem 'Unclosed quote'.
help me please.

**Comment by ben-eb** [comment]
You have an unclosed string in your CSS which is why this error is being thrown; i.e.

```css
div:before {
  content: '
/*         ^ */
}
```

The error should have told you where this was located so that you can fix it. 😄
